#!/bin/bash

REPO1="https://formulae.brew.sh/api/cask/yandex-cloud-cli.json"
REPO2="https://storage.yandexcloud.net/yandexcloud-yc/install.sh"

NAME1=jq
LINUX=checkLinux

usage() {
  cat <<EOF

Usage: 
    $(basename "${BASH_SOURCE[0]}") [-h] [-c] value1 [-t] value2

Available options:
    -h, --help      Print this help and exit
    -t, --template  Path to the template with the list of tools that will be installed
    -c, --config    Path to the configuration file main.tf
EOF
  exit
}

logger() {
    log_file="./script.log"
    > "$log_file"
    exec > >(tee -a "$log_file") 2>&1
}

ifUsingHelp() {
    if [[ "$1" == "-h" || "$1" == "--help" ]]; then
        usage
        exit 0
    fi
 }

checkVersion() {
    if [ $NAME1 != "terraform" ]; then
        $NAME1 version | awk '{print $4}'
    else
        $NAME1 version | awk '{print $2}' | head -1
    fi
}

checkLatestVersion() {
    if [ $NAME1 != "terraform" ]; then
         curl -sSL $REPO1 | jq -r ".version"
    else
         curl -sSL $REPO1 | jq -r ".tag_name"
    fi
}

delimitationLine() {
    echo ""
    echo "-----------------------------------------------------------------------------------------------------------" 
    echo ""
}

isInstalled() {
    echo "Checking if the "$NAME1 "is installed..."
    if [ $(command -v $NAME1) ]; then
        echo "The programm "$NAME1" is allready installed"
    else
        echo "Error: "$NAME1" is not installed."
        delimitationLine
        installProgram
    fi
    delimitationLine
}

checkCurrentVersion() {
    v1=$(checkVersion)
    v2=$(checkLatestVersion)

    if [ $NAME1 == "yc" ]; then
        v2=$(echo "$v2" | awk -F. -v OFS=. '{ $2++; print }')
    else
        :
    fi

    echo -n "Checking the current version of the "$NAME1": "
    checkVersion
    delimitationLine
    echo -n "Checking the latest version of the "$NAME1": "
    checkLatestVersion
    delimitationLine

    if [ $v1 == $v2 ]; then
        echo -n "The latest version of the "$NAME1 "is allready installed: "
	checkVersion
    else
        echo "Need to update "$NAME1 "to the latest version" $v2
        delimitationLine
        installProgram
    fi
    delimitationLine
}

isTerraform() {
    if [[ $NAME1 != "terraform" && $NAME1 != "jq" ]]; then
	curl -sSL $REPO2 | bash
	echo ""
	echo "Starting new shell..."
    elif [ $NAME1 == "jq" ]; then
        installJq
    else
        #isKali 
        echo "ITS OK"
    fi
}

isKali() {
    if [ $LINUX  != "Kali GNU/Linux" ]; then
        installTerraform1
    else
        installTerraform2
    fi
}

installProgram() {
    echo "Installing "$NAME1"..."
    delimitationLine
    isTerraform
}

installJq() {
    sudo apt-get install jq
    jq --version
}

installTerraform1() {
    sudo apt install -y gnupg software-properties-common curl
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    echo "Need to make update your system..."
    delimitationLine
    updateSystem
    sudo apt-get install terraform
    echo ""
    if [ $(command -v $NAME1 ) ]; then
        echo "The program "$NAME1" installed correctly."
    else
        installTerraform2
    fi
    delimitationLine
}

installTerraform2() {
    concatVersion
    getUrl
    getFile
    wget -O $(getFile) $(getUrl)
    sudo unzip $(getFile) -d /usr/local/bin
}

concatVersion() {
    v=$(checkLatestVersion)
    file="${v:1}" 
    echo $file
}

getUrl() {
    version=$(concatVersion)
    url="https://releases.hashicorp.com/terraform/"
    file_name1="/terraform_"
    file_name2="_linux_amd64.zip"
    file_url="${url}${file}${file_name1}${version}${file_name2}"
    echo $file_url
}

getFile() {
    version=$(concatVersion)
    file_name1="terraform_"
    file_name2="_linux_amd64.zip"
    file_version="${file_name1}${version}${file_name2}"
    echo $file_version
}

optionSelection() {
    read -p "Do you want to proceed? (yes/no) " yn 

    case $yn in
        yes ) echo ok, we will proceed;;
        no ) echo exiting...;
	    exit 0;;
        * ) echo invalid response;
            exit 1;;
    esac
}

updateSystem() {
    echo "Updating your system:"
    sudo apt-get update
    delimitationLine
}

checkLinux() {
    delimitationLine
    echo -n "Checking the installed operating system: "

    if [ -f /etc/*release* ]; then
        . /etc/*release*
        echo $NAME
    else
        echo "File /etc/*release* not found!"
    fi
    delimitationLine
}

createProfileCLI() {
    echo "Starting to create a CLI profile..."
    yc init
    delimitationLine
    echo "Check your CLI profile settings:"
    delimitationLine
    yc config list 
    delimitationLine
}

variablesToMain_tf() {
    output=$(yc config list)

    awk -F': ' '/token/ { printf "s/token *= *\".*\"/token = \"%s\"/g\n", $2 }
                /cloud-id/ { printf "s/cloud_id *= *\".*\"/cloud_id = \"%s\"/g\n", $2 }
                /folder-id/ { printf "s/folder_id *= *\".*\"/folder_id = \"%s\"/g\n", $2 }
                /compute-default-zone/ { printf "s/zone *= *\".*\"/zone = \"%s\"/g\n", $2 }
  '     <<< "$output" > sed_script.sed

    sed -i -f sed_script.sed main.tf
    rm sed_script.sed
}

startTerraform() {
    echo "Terraform initialisation begins: "
    terraform init
    delimitationLine
    echo "Terraform planning check: "
    delimitationLine
    terraform plan
    delimitationLine
    echo "Confirm the settings:"
    delimitationLine
    terraform apply
    delimitationLine
}

logger

checkLinux

ifUsingHelp $1
isInstalled

NAME1=yc
isInstalled
checkCurrentVersion

NAME1=terraform
REPO1="https://api.github.com/repos/hashicorp/terraform/releases/latest"

isInstalled
checkCurrentVersion

createProfileCLI
variablesToMain_tf
startTerraform
